### ISSUE TITLE
Transfer this repo out of putaindecode?

### ISSUE THREAD

**Issue by MoOx** [kud/memo#5]
Does not really make sense these days...
Repo name should be deprecated and use a new one.
Who want to take care of this repo?

**Comment by kud** [comment]
I can take it back to my own "orga".

**Comment by MoOx** [comment]
Doing it.

**Comment by MoOx** [comment]
Hum. Please go to settings, first page, at the bottom then transfert it to yourself, otherwise I need to transfert to me, then to you.
